#TODO: ?????????? yml
server:
  port: 9999

spring:
  datasource:
    url: mongodb://localhost:27017/auditbase
    username: daniel
    password: 16052002
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
     trust-all: true
    topic: audit-queue